services:
  jenkins-master:
    build:
      context: ./setup/docker/jenkins
    image: custom-jenkins:latest
    container_name: jenkins-master
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins-net
    env_file:
      - .env

volumes:
  jenkins_home:

networks:
  jenkins-net:
