# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js v22.17.1
      uses: actions/setup-node@v4
      with:
        node-version: v22.17.1
        cache: 'npm'
        cache-dependency-path: ./api/package-lock.json
    - run: npm ci
      working-directory: ./api
    - run: node getPokemon/test.js
      working-directory: ./api
    - run: |
        func start --verbose &
        sleep 10
        pushd ../test/api
        npm run test:bruno
      working-directory: ./api
